### ISSUE TITLE
build script for aarch64

### ISSUE THREAD

**Issue by michaelherger** [ralph-irving/faad2#1]
I'm trying to build for aarch64 (Rock64). I tried to use the script for armhf, replacing references to this platform with aarch64. But oh well, it's not that easy. Would you have any idea what I should be trying?

**Comment by ralph-irving** [comment]
I would start by removing '-march=armv6 -mfloat-abi=hard -mfpu=vfp' from CFLAGS if you are building on an aarch64 system.

**Comment by michaelherger** [comment]
Bingo! That resulted in a working binary! There are quite a few warnings along the way. Like

```main.c:1141:58: warning: pointer targets in passing argument 4 of ‘alac_init’ differ in signedness [-Wpointer-sign]
```

or ```../common/mp4ff/mp4ff.h:176:9: note: expected ‘unsigned int *’ but argument is of type ‘int *’```

How would you go about them?

**Comment by ralph-irving** [comment]
Those warnings are present when building for other platforms as well.  Newer gcc versions also tend to produce more warnings as well. The signed mismatch warning I should look into but they have been there for a very long time and in my experience trying to fix them sometimes breaks what was working fine before.
When you get a chance would you build faad using the standard linux script?  If it does then I can likely simplify the build scripts to only 2 for linux...arm without floating point support and everything else.

**Comment by michaelherger** [comment]
Heh... buildme-linux.sh actually gives an almost clean build log with only a hand full of warnings. Excellent!

I had to update config.guess and config.sub to make it work though. That's probably why I first tried to create a custom build script. Shall I submit a pull request?

**Comment by ralph-irving** [comment]
I've merged your pull request and confirmed that I can build a working i386 and armhf faad with the change and buildme-linux.sh.
