### ISSUE TITLE
Using stdin

### ISSUE THREAD

**Issue by philippe44** [ralph-irving/faad2#5]
Hi - Do you think there is a chance to be able to use stdin?

**Comment by ralph-irving** [comment]
The faad2 frontend already has support for stdin and stdout as well.
https://github.com/ralph-irving/faad2/blob/master/frontend/main.c#L477
What is your use case?

**Comment by philippe44** [comment]
Sorry, I was not clear. I meant stdin for mp4, not for just for aac type

**Comment by ralph-irving** [comment]
faad alac (mp4) handling supports
  -j X  Jump - start output X seconds into track (MP4 files only).
 -e X  End  - end output X seconds into track (MP4 files only).
which is why stdin is not supported for the format.
-j and -e are currently used in lms convert.conf rules to start playback anywhere within the file.
Perhaps I could add another option to enable stdin for mp4 files too that would disable the jump/end options.  Would that be a viable option?

**Comment by philippe44** [comment]
Yes, that would be perfect. When there is no -j or- e, allowing stdin would be great

**Comment by ralph-irving** [comment]
Unfortunately, the mp4 parsing routines expect to be able to seek to any position in the file and fail part way through when reading from stdin never locating the audio track.

**Comment by philippe44** [comment]
ah ... crap. Do you think this is fixable? Shall I have a look, it's in the mp4ff part? I'm asking that b/c if this does not work, I'll have to find a completely different idea for the mp4 remote stream playback :-(

**Comment by ralph-irving** [comment]
Yes, it's in common/mp4ff/mp4atom.c for starters. I haven't had a chance to investigate more yet, hopefully tomorrow.   I've pushed my mp4 stdin changes to faad to the mp4stdin branch, if you do decide to have a look.

**Comment by philippe44** [comment]
Thanks very much - in parallel I'm exploring a mp4 to ADTS extractor in Perl/LMS. Basics are working but I'm not sure this is a satisfactory route

**Comment by philippe44** [comment]
I've pushed a working mp4 to aac demuxer in LMS (Perl) and another patch that allows more than one transcoding rule per audio format couple. So if some don't like the built-in demuxer, even if faad can't do 'I' mp4 objects, they can use a rule to have ffmpeg for these 'I' sources (including alac) leave faad for all the mp4 'F' and aac 'I' sources. The header rebuilding allows seeking in any case.

Having faad as the unique mp4/aac transcoder would be great, though :-)
