### ISSUE TITLE
Function declaration & use inconsistency shown by up clang under Termux

### ISSUE THREAD

**Issue by bpa-code** [ralph-irving/faad2#7]
This is just a note for the record - not sure whether it is worthwhile making a change.

I'm doing LMS for Termux port and Termux uses clang 18.1 which is slightly different from gcc and has flagged an error.

It has shown up related errors in frontend files audio.h, audio.c and main.c regarding function int write_audio_file_raw . It looks like a change that was never completed. 

In audio.h - the function name is spelt with an extra "S" ending with "...file_rawS and not "...file_raw" and has 4 parameters
Line 59 int write_audio_file_rawS(audio_file *aufile, void *sample_buffer, int samples, int offset);

In audio.c  - declaration of function with only 3 parameters
Line 123-124
int write_audio_file_raw(audio_file *aufile, void *sample_buffer,
                             unsigned int samples)

In main.c - use of function with 4 parameters - 4th param "delay" does not seems to be used in calling routine
Line 1282
          if (write_audio_file_raw(aufile, sample_buffer, sample_count, delay) == 0)

**Comment by ralph-irving** [comment]
Looks like that confusion was in the original faad2 logitech patch applied at commit 153b385ce51afc2b7101f6ee64f0c92e5ece245b and we should clean it up.

I think this patch should fix it.  Let me know and I'll commit it.  Thanks for pointing it out.

[cleanup-write_audio_file_raw.patch.txt](https://github.com/ralph-irving/faad2/files/14958572/cleanup-write_audio_file_raw.patch.txt)
